"""Add Review Model

Revision ID: b157b92556cb
Revises: ec961361e99e
Create Date: 2025-05-25 22:01:53.341622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b157b92556cb'
down_revision = 'ec961361e99e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
